## Numpy

### array( ) / shape( )

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])                  # take a python list
print('array1 type: ', type(array1))        # np.array function return ndarray
print('array1 array shape: ', array1.shape) # it has one dimention and three data
print('\n')

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type: ', type(array2))
print('array2 array shape: ', array2.shape) # two dimention and three data per each one dimention
print('\n')

array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array shape: ', array3.shape) # two dimention but it has only one dimention which is contained three data

array1 type:  <class 'numpy.ndarray'>
array1 array shape:  (3,)


array2 type:  <class 'numpy.ndarray'>
array2 array shape:  (2, 3)


array3 type:  <class 'numpy.ndarray'>
array3 array shape:  (1, 3)


In [3]:
print('array1: {:0}dimention, array2: {:1}dimentions, array3:{:2}dimentions'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1dimention, array2: 2dimentions, array3: 2dimentions


### Data type of ndrray
- ndarray can input number, string, bool
- but it can contain only same data type

In [4]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
# If list is contain with different type of data, ndarray is converted into more bigger data type in batches.
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype, '\n') # number 1, 2 are tranformed by string ('1','2','test')

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int 1, 2 are transformed by float

['1' '2' 'test'] <U11 

[1. 2. 3.] float64


Function of astype( )
- when want to save the memory, can put the type that you want to allocate

In [6]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') 
print(array_float, array_float.dtype,'\n')

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype,'\n')

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64 

[1 2 3] int32 

[1 2 3] int32


np.array( )
- Value of ndarray return from 0 to index value -1

In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


### zeros( ), ones( )
- zeros returns ndarray with the corresponding shape filled with zero all values when entering the shape of a tuple as a function factor.
- ones is similar with zeros.
- all of different thing is ones return ndarray which has relevant shape filled with 1

In [8]:
import numpy as np
array= np.array(
                [[[1, 1], 
                  [1, 1],
                  [1, 1]]
                 ,[[1, 1], 
                  [1, 1],
                  [1, 1]]]
)
array.shape

(2, 3, 2)

In [9]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape, '\n')

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [12]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape: ', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape: ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# transform from 3 dim array to 2 dim array
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape: ', array5.shape)

# transform from 1 dim array to 2 dim array
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape: ', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:  (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:  (8, 1)


### Indexing ( Extract Single Value )

In [15]:
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)

value = array1[2]
print('value: ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int32'>


In [16]:
print('The last value: ', array1[-1], 'The second value from the last: ', array1[-2])

The last value:  9 The second value from the last:  8


In [17]:
array1[0]=9
array1[8]=0
print('array1: ', array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [18]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('The value (row=0, col=0) of index: ', array2d[0,0])
print('The value (row=0, col=1) of index: ', array2d[0,1])
print('The value (row=1, col=0) of index: ', array2d[1,0])
print('The value (row=2, col=2) of index: ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The value (row=0, col=0) of index:  1
The value (row=0, col=1) of index:  2
The value (row=1, col=0) of index:  4
The value (row=2, col=2) of index:  9


### Indexing ( Slicing )

In [19]:
print(array1, '\n')

# Omitting the start index before the ':' symbol automatically counts as the first index-in-zero
array1 = np.arange(start = 1, stop=10)
array4 = array1[:3]
print(array4)

# Omitting the finish index after the ':' symbol automatically counts as the last index
array5 = array1[3:]
print(array5)

# Omitting the start/finish index befor and after the ':' symbol automatically count as whole index
array6 = array1[:]
print(array6)

[9 2 3 4 5 6 7 8 0] 

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
# when if it is two dimentions
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d, '\n')

print('array2d[0:2, 0:2]\n',array2d[0:2, 0:2], '\n')
print('array2d[1:3, 0:3]\n',array2d[1:3, 0:3], '\n')
print('array2d[1:3, :]\n',array2d[1:3, :], '\n')
print('array2d[:, :]\n',array2d[:, :], '\n')
print('array2d[:2, 1:]\n',array2d[:2, 1:], '\n')
print('array2d[:2, 0]\n',array2d[:2, 0], '\n')

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[0:2, 0:2]
 [[1 2]
 [4 5]] 

array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]] 

array2d[1:3, :]
 [[4 5 6]
 [7 8 9]] 

array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[:2, 1:]
 [[2 3]
 [5 6]] 

array2d[:2, 0]
 [1 4] 



In [21]:
# Return one dimention ndarray when remove the last index at two dimentions
print(array2d[0])
print(array2d[1])

print('array2d[0] shape: ', array2d[0].shape, 'array2d[1].shape: ', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape:  (3,) array2d[1].shape:  (3,)


### Indexing( Fancy Indexing )

In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 2] => ', array4.tolist())

array5= array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0, 1], 2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### Indexing( Boolean Indexing )

In [23]:
array1d = np.arange(start=1, stop=10)
# applt Boolean Indexing(array1d > 5) inside of [ ]
array3 = array1d[array1d > 5]
print('The value of "array1d > 5": ', array3)

The value of "array1d > 5":  [6 7 8 9]


### sort( ) & argsort( )

In [24]:
org_array = np.array([3, 1, 9, 5])
print('Original matrix: ', org_array)

# sorted by np.sort( )
sort_array1 = np.sort(org_array)
print('Returning matrix after sorted by np.sort( ): ', sort_array1)
print('Original matrix after sorted by np.sort( )', org_array)

# sorted by ndarray.sort( )
sort_array2 = org_array.sort()
print('Returning matrix after sorted by org_array.sort(): ', sort_array2)
print('Original matrix after sorted by org_array.sort():', org_array)

Original matrix:  [3 1 9 5]
Returning matrix after sorted by np.sort( ):  [1 3 5 9]
Original matrix after sorted by np.sort( ) [3 1 9 5]
Returning matrix after sorted by org_array.sort():  None
Original matrix after sorted by org_array.sort(): [1 3 5 9]


In [25]:
array2d = np.array([[8, 12],
                    [7, 1 ]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('Sorted by direction of lows:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('Sorted by direction of columns: \n', sort_array2d_axis1)

Sorted by direction of lows:
 [[ 7  1]
 [ 8 12]]
Sorted by direction of columns: 
 [[ 8 12]
 [ 1  7]]


In [26]:
# when the original matrix was sorted, 
# if it need to index about the original one, use np.argsort( )

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('The original of index when matrix sort: ', sort_indices)

<class 'numpy.ndarray'>
The original of index when matrix sort:  [1 0 3 2]


In [27]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indice_asc = np.argsort(score_array)
print('The index of score_array when sorted by ascent: ', sort_indice_asc)
print('Return value of name_array sorted by ascent: ', name_array[sort_indice_asc])

The index of score_array when sorted by ascent:  [0 2 4 1 3]
Return value of name_array sorted by ascent:  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### Matrix dot product

In [30]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

### transpose matrix

In [32]:
A = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(A)
print('Transpose A matrix:\n ', transpose_mat)

Transpose A matrix:
  [[1 3]
 [2 4]]
