# Import Numpy

In [1]:
import numpy as np

# Transform np.array

In [2]:
# list
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
# transform numpy array
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
# If you want to change mylist to np.array
# It needs to define object
arr = np.array(mylist)
arr

array([1, 2, 3])

# Matrix

In [7]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
mymatrix = np.array(mylist)

In [9]:
mymatrix.shape

(3, 3)

# make range array

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
# broadcast which is one of function of numpy is useful compare with python list
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [13]:
np.ones(4) * 100

array([100., 100., 100., 100.])

# linspace
- 등 간격으로 나누기

In [14]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
len(np.linspace(0, 10, 20))

20

# np.eye
- Making identity matrix

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random.rand
- 0과 1에 대한 균등분포에서 임의의 샘플 출력
- 모든 난수가 uniform distribution이기 때문에 특정숫자가 나올 확율은 동일하다

In [17]:
np.random.rand(5, 5)

array([[0.43868979, 0.43542221, 0.39401157, 0.9013644 , 0.07902728],
       [0.83769441, 0.22357155, 0.26595917, 0.53552273, 0.05360952],
       [0.69668987, 0.23051713, 0.64316023, 0.63332203, 0.25453848],
       [0.87515549, 0.34261393, 0.25736066, 0.34495982, 0.34336573],
       [0.38897947, 0.47391326, 0.71781021, 0.01850403, 0.9104647 ]])

# np.random.randn
- 표준 정규 분포에서 하나 이상의 샘플 출력
- 표준 정규 분포의 평균은 0이고 표준편차는 1

In [18]:
np.random.randn(10)

array([-1.51985977, -0.88787224, -0.02168543,  0.10766315, -0.07554359,
       -0.22494074,  0.75791299, -0.08772776, -0.66131283, -1.78224992])

# np.random.randint
- 최솟값을 포함하고 최댓값을 제외한 범위에서 임의의 정수를 반환함

In [19]:
np.random.randint(1, 100, 10)

array([45, 27, 97, 62, 23, 62, 42, 58, 74, 25])

# np.random.seed
- 난수를 설정함

In [20]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

# reshape
- 차원의 형태를 바꿀때 사용
- 차원의 형태를 바꿀때 형식을 맞추는 게 중요

In [21]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# argmax / argmin
- 최대/최소의 인덱스 값을 반환

In [23]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [24]:
ranarr.max()

48

In [25]:
ranarr.min()

10

In [26]:
ranarr.argmax()

1

In [27]:
ranarr.argmin()

6

# Indexing

In [28]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[8]

8

In [30]:
arr[1:5]

array([1, 2, 3, 4])

In [31]:
arr[0:5], arr[:5]

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [32]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# Broadcast

In [33]:
arr, arr + 100

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110]))

In [34]:
new_arr = arr / 2
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [35]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

# Slicing

- 새로운 객체에 slicing을 해도 원래의 배열을 가리킨다.
- slicing을 기반으로 재할당에 Broadcasting을 수행하면 기존 배열에도 영향을 끼칠 수 있다.

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [40]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [41]:
# slice_of_arr의 영향을 받아 Broadcasting이 적용되었다.
# 즉 slice_of_arr이 arr의 배열을 가리키고 있다는 것이다.
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
# 이를 방지하기 위해서 .copy() 메소드를 적용해야 한다.
arr_copy = arr.copy()
arr_copy[:]=1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Boolean indexing


In [47]:
arr_2d = np.array([[5, 10, 15],
                   [20, 25, 30],
                   [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d.shape

(3, 3)

In [50]:
# array[행 인덱스] => 행 Matrix 출력
arr_2d[1], arr_2d[1][1]

(array([20, 25, 30]), 25)

In [51]:
# array[행 인덱스, 열 인덱스] => 행/열이 Indexing된 matrix 출력
arr_2d[1,1]

25

In [52]:
arr_2d[2,2]

45

In [53]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [57]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
# 4가 Broadcasting이 되어 모든 요소와 비교함
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [61]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [63]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
arr[arr==2]

array([2])

In [65]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])